const loremText = `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sagittis aliquam malesuada bibendum arcu vitae elementum curabitur. Sed turpis tincidunt id aliquet risus feugiat in ante metus. Duis at consectetur lorem donec massa sapien faucibus. Sed tempus urna et pharetra pharetra massa massa. Auctor elit sed vulputate mi sit amet mauris. Nisi quis eleifend quam adipiscing vitae proin sagittis nisl rhoncus. Sodales neque sodales ut etiam sit amet nisl purus. Viverra nibh cras pulvinar mattis nunc sed blandit libero. Sit amet nisl purus in mollis nunc sed. Tristique senectus et netus et malesuada fames. Varius quam quisque id diam.
At tempor commodo ullamcorper a lacus vestibulum. Aliquet enim tortor at auctor urna. Neque laoreet suspendisse interdum consectetur libero id faucibus nisl tincidunt. Platea dictumst quisque sagittis purus sit amet. Posuere ac ut consequat semper viverra nam libero justo laoreet. Arcu odio ut sem nulla pharetra diam. Pellentesque dignissim enim sit amet venenatis urna cursus eget nunc. Ultrices vitae auctor eu augue. Arcu cursus vitae congue mauris. Bibendum at varius vel pharetra vel turpis nunc. Cursus sit amet dictum sit amet justo donec enim diam.
Volutpat commodo sed egestas egestas. Nunc mattis enim ut tellus elementum sagittis. Vestibulum lectus mauris ultrices eros in cursus. Id velit ut tortor pretium viverra. Nisl tincidunt eget nullam non nisi est sit amet facilisis. Faucibus ornare suspendisse sed nisi lacus sed viverra tellus in. Diam sollicitudin tempor id eu nisl. Varius duis at consectetur lorem donec massa sapien faucibus et. Dignissim enim sit amet venenatis urna. Neque vitae tempus quam pellentesque nec nam aliquam. Arcu non odio euismod lacinia. Pulvinar pellentesque habitant morbi tristique senectus et netus et malesuada. Senectus et netus et malesuada fames ac turpis egestas integer. Quis viverra nibh cras pulvinar mattis nunc sed. Eget duis at tellus at urna condimentum mattis. Orci dapibus ultrices in iaculis nunc sed augue. Maecenas volutpat blandit aliquam etiam erat velit. Malesuada proin libero nunc consequat interdum. Sagittis eu volutpat odio facilisis mauris sit amet.
Id ornare arcu odio ut sem. Et netus et malesuada fames. Eleifend quam adipiscing vitae proin sagittis nisl rhoncus mattis. Lacus viverra vitae congue eu consequat ac felis. Scelerisque eu ultrices vitae auctor eu augue ut lectus arcu. Scelerisque varius morbi enim nunc faucibus a pellentesque sit. Neque convallis a cras semper auctor neque. At varius vel pharetra vel turpis nunc eget lorem dolor. Nunc non blandit massa enim nec dui nunc mattis enim. Turpis massa sed elementum tempus egestas sed sed risus pretium.
Pretium fusce id velit ut tortor pretium viverra. A diam sollicitudin tempor id eu nisl nunc. Suspendisse interdum consectetur libero id faucibus. Adipiscing vitae proin sagittis nisl rhoncus mattis rhoncus urna. Duis tristique sollicitudin nibh sit amet commodo nulla. Adipiscing diam donec adipiscing tristique risus nec. Porttitor rhoncus dolor purus non. At auctor urna nunc id cursus metus. Et malesuada fames ac turpis egestas maecenas pharetra convallis. Pharetra et ultrices neque ornare aenean euismod elementum nisi. Scelerisque varius morbi enim nunc faucibus a pellentesque. Vestibulum rhoncus est pellentesque elit ullamcorper. Aliquet enim tortor at auctor. Pharetra et ultrices neque ornare aenean. Pulvinar neque laoreet suspendisse interdum. Vehicula ipsum a arcu cursus vitae congue mauris rhoncus aenean.
`.split(" ")

export default {
  lorem: loremText
}